"""empty message

Revision ID: 86fd83c7a373
Revises: 2e4536aedcdc
Create Date: 2024-09-06 21:07:19.957927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86fd83c7a373'
down_revision: Union[str, None] = '2e4536aedcdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tokens', ['id'])
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('users', 'activated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activated', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'tokens', type_='unique')
    # ### end Alembic commands ###
