"""init

Revision ID: 89a1a3c3ee57
Revises: 6a1af7c411c1
Create Date: 2024-08-18 16:33:45.219105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89a1a3c3ee57'
down_revision: Union[str, None] = '6a1af7c411c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gravatar')
    op.drop_column('users', 'two_factor_option')
    op.drop_column('users', 'jobtitle')
    op.drop_column('users', 'remember_token')
    op.drop_column('users', 'reset_password_code')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'activated_at')
    op.drop_column('users', 'two_factor_secret')
    op.drop_column('users', 'activation_code')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'two_factor_enrolled')
    op.drop_column('users', 'employee_num')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_num', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('two_factor_enrolled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('activation_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('two_factor_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('activated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('reset_password_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('remember_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('jobtitle', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('two_factor_option', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('gravatar', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
