"""empty message

Revision ID: bf7ea4482b2a
Revises: 070c8ae5def2
Create Date: 2024-09-16 21:35:33.419719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7ea4482b2a'
down_revision: Union[str, None] = '070c8ae5def2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'companies', ['id'])
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'companies', type_='unique')
    # ### end Alembic commands ###
